#!/bin/bash

configurl="https://raw.githubusercontent.com/AfzGit/quick-vim/main/init.vim"

# Installing the config file
curl -s "$configurl" >> /home/$USER/.vimrc
echo "Config file installed"

# Installing VIM-Plug
echo "Add plugins in ~/.vimrc file and then run :PlugInstall"
echo "Done."
